<!ELEMENT dataset (
        Configuration*,
        Lang*,
        Room*,
        Tag*,
        T_user*)>

        <!ELEMENT Configuration EMPTY>
        <!ATTLIST Configuration
                CONF_KEY CDATA #REQUIRED
                CONF_VALUE CDATA #REQUIRED
                >

        <!ELEMENT Lang EMPTY>
        <!ATTLIST Lang
                ID CDATA #REQUIRED
                NAME CDATA #REQUIRED
                >

        <!ELEMENT Room EMPTY>
        <!ATTLIST Room
                ID CDATA #REQUIRED
                NAME CDATA #REQUIRED
                ACTIVE CDATA #REQUIRED
                >

        <!ELEMENT Tag EMPTY>
        <!ATTLIST Tag
                TAG CDATA #REQUIRED
                TEXT CDATA #REQUIRED
                LANG_ID CDATA #REQUIRED
                >

        <!ELEMENT T_user EMPTY>
        <!ATTLIST T_user
                ID CDATA #REQUIRED
                NAME CDATA #REQUIRED
                ACTIVE CDATA #REQUIRED
                LANG_ID CDATA #REQUIRED
                >