-- v2.0.0_5 - English Tags

INSERT INTO t_tag (tag, lang_id, text) VALUES
      ('PLAYER_WELCOME', 'en', 'Welcome! I just added you to my database.\nWhen you need help you only have to send me the command /help\nThank you for joining!'),
      ('ALL_MESSAGES_SENT', 'en', 'All messages sent.'),
      ('GO_BACK', 'en', '← Go back'),
      ('ACCEPT', 'en', 'Accept'),
      ('CANCEL', 'en', 'Cancel'),

      ('USER_LANG_CHANGE', 'en', 'Choose your language:'),
      ('USER_LANG_CHANGED', 'en', 'Language changed successfully.'),

      ('GAME_HELP', 'en', 'Welcome to the help menu of {0} version {1}\n\nYou can check for help here: {2}\n\nEnjoy the bot and... Let´s play!\n\nMade by {3}.'),
      ('GAME_CREATING', 'en', 'Hold on, I´m creating the game...'),
      ('GAME_CREATED_GROUP', 'en', 'I already created the game!'),
      ('GAME_SELECT_MAX_PLAYERS', 'en', '\nSelect max number of players:'),
      ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'en', 'The maximum number of players is <b>{0}</b>.'),
      ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'en', '<b>{0}</b> players have joined:'),
      ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'en', '<b>{0}</b> player/s have voted to delete the game.'),
      ('GAME_DELETED', 'en', 'Game deleted.'),
      ('GAME_DELETION_USER', 'en', '{0}´s game has been deleted.'),
      ('GAME_DELETION_ALL', 'en', 'All games have been deleted.'),
      ('GAME_DELETION_FORCED', 'en', 'Sorry, the game has been deleted by an admin. You can start a new game.'),
      ('GAME_LEAVE', 'en', 'Leave game'),
      ('GAME_LEFT', 'en', 'You left the game.'),
      ('GAME_JOIN_BUTTON', 'en', 'Join game'),
      ('GAME_CONFIGURE_BUTTON', 'en', 'Configure game'),
      ('GAME_START_BUTTON', 'en', 'Start game'),
      ('GAME_DELETE_BUTTON', 'en', 'Delete game'),
      ('GAME_CHANGE_MAX_N_PLAYERS', 'en', 'Change number of max players.'),

      ('PLAYER_CREATED_GAME', 'en', 'I created a game in the group, you can configure it there.'),
      ('PLAYER_JOINING', 'en', 'Hold on, you are joining the game...'),
      ('PLAYER_JOINED', 'en', 'You joined the game.'),
      ('PLAYER_VOTED_DELETION', 'en', 'You voted to delete the game.'),

      ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'en', 'This command must be sent privately to the bot.'),
      ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'en', 'This command must be sent in a group in which the bot is.'),
      ('ERROR_UNKNOWN', 'en', 'Unknown error.'),
      ('ERROR_USER_ALREADY_REGISTERED', 'en', 'You´re already registered. Write /help for more information.'),
      ('ERROR_GAME_ALREADY_CREATED', 'en', 'There is an active game in this group or the creator has an active game on another group.'),
      ('ERROR_GAME_ALREADY_FILLED', 'en', 'The game has already reached the maximum of players.'),
      ('ERROR_GAME_ALREADY_STARTED', 'en', 'The game has already started.'),
      ('ERROR_GAME_ONLY_CREATOR_CAN_CONFIGURE', 'en', 'Only the creator can configure it.'),
      ('ERROR_GAME_ONLY_CREATOR_CAN_DELETE', 'en', 'Only the creator can delete it.'),
      ('ERROR_GAME_ONLY_CREATOR_CAN_START', 'en', 'Only the creator can start the game.'),
      ('ERROR_GAME_DOESNT_EXISTS', 'en', 'There is no game initiated in this group.'),
      ('ERROR_GAME_USER_DOESNT_EXISTS', 'en', 'You are not registered. Input /start in private.'),
      ('ERROR_GAME_NOT_FILLED', 'en', 'The game has not reached the minimum number of players.'),
      ('ERROR_GAME_NOT_STARTED', 'en', 'The game has not started.'),
      ('ERROR_PLAYER_NO_GAMES', 'en', 'You have no active games.'),
      ('ERROR_PLAYER_ALREADY_PLAYING', 'en', 'You are already playing a game.'),
      ('ERROR_PLAYER_ALREADY_JOINED', 'en', 'Ya estas participando en esta partida.'),
      ('ERROR_PLAYER_DOES_NOT_EXISTS', 'en', 'You have not joined any game.'),
      ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'en', 'You have already voted to delete the game.');
